Fix remote muting jigasi participants (#258)
* fix: NPE when sip participants is leaving the call.

SEVERE: [108354] org.jitsi.jigasi.util.Util.lambda$injectSoundFile$0().295 Error playing:sounds/ParticipantLeft.opus
org.jitsi.service.neomedia.TransmissionFailedException: java.lang.NullPointerException
	at org.jitsi.impl.neomedia.MediaStreamImpl.injectPacket(MediaStreamImpl.java:3775)
	at org.jitsi.jigasi.SoundNotificationManager.injectSoundFileInStream(SoundNotificationManager.java:349)
	at org.jitsi.jigasi.SoundNotificationManager.lambda$injectSoundFile$0(SoundNotificationManager.java:290)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.jitsi.impl.neomedia.MediaStreamImpl.injectPacket(MediaStreamImpl.java:3767)
	... 3 more

* fix: Uses private method to get connection.

* fix: Muting jigasi participants and handling start muted.

* fix: Lock when initializing providers.

"org.jitsi.impl.osgi.framework.AsyncExecutor" #14 daemon prio=5 os_prio=31 tid=0x00007ffe34c30000 nid=0xa703 in Object.wait() [0x000070000913c000]
   java.lang.Thread.State: RUNNABLE
	at org.jivesoftware.smack.SmackConfiguration.getVersion(SmackConfiguration.java:96)
	at org.jivesoftware.smack.provider.ProviderManager.<clinit>(ProviderManager.java:122)
	at org.jitsi.xmpp.extensions.jitsimeet.MediaPresenceExtension.registerExtensions(MediaPresenceExtension.java:59)
	at org.jitsi.jigasi.JigasiBundleActivator.serviceChanged(JigasiBundleActivator.java:284)
	at org.jitsi.impl.osgi.framework.launch.EventDispatcher$Command.run(EventDispatcher.java:128)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
	at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)

"org.jitsi.impl.osgi.framework.AsyncExecutor" #13 daemon prio=5 os_prio=31 tid=0x00007ffe339a4800 nid=0xa803 in Object.wait() [0x0000700009038000]
   java.lang.Thread.State: RUNNABLE
	at org.jivesoftware.smack.initializer.UrlInitializer.initialize(UrlInitializer.java:54)
	at org.jivesoftware.smack.SmackInitialization.loadSmackClass(SmackInitialization.java:237)
	at org.jivesoftware.smack.SmackInitialization.parseClassesToLoad(SmackInitialization.java:198)
	at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:168)
	at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:153)
	at org.jivesoftware.smack.SmackInitialization.<clinit>(SmackInitialization.java:119)
	at org.jivesoftware.smack.SmackConfiguration.getVersion(SmackConfiguration.java:96)
	at org.jivesoftware.smack.AbstractXMPPConnection.<clinit>(AbstractXMPPConnection.java:109)
	at org.jitsi.jigasi.xmpp.CallControlMucActivator.<clinit>(CallControlMucActivator.java:83)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:305)
	at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)
	at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
	at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
	at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)

"AccountManager.loadStoredAccounts" #23 daemon prio=5 os_prio=31 tid=0x00007ffe33a8d800 nid=0x29107 in Object.wait() [0x0000700009d6d000]
   java.lang.Thread.State: RUNNABLE
	at org.jitsi.xmpp.extensions.jingle.JingleIQProvider.<init>(JingleIQProvider.java:44)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initialize(ProtocolProviderServiceJabberImpl.java:1800)
	- locked <0x00000006c002e0d8> (a java.lang.Object)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderFactoryJabberImpl.createService(ProtocolProviderFactoryJabberImpl.java:173)
	at net.java.sip.communicator.service.protocol.ProtocolProviderFactory.loadAccount(ProtocolProviderFactory.java:1010)
	at net.java.sip.communicator.service.protocol.AccountManager.doLoadStoredAccounts(AccountManager.java:218)
	at net.java.sip.communicator.service.protocol.AccountManager.loadStoredAccounts(AccountManager.java:468)
	at net.java.sip.communicator.service.protocol.AccountManager.runInLoadStoredAccountsThread(AccountManager.java:585)
	at net.java.sip.communicator.service.protocol.AccountManager.access$100(AccountManager.java:37)
	at net.java.sip.communicator.service.protocol.AccountManager$2.run(AccountManager.java:510)

* ref: Simplifies code.

* fix: Sets JitsiMeetTools RequestListener when setting up sip call.

And removes it when call is ended.

* fix: Show correct presence status in meeting when remotely muted.

* fix: Sending SIP Info messages only on established call.