fix(whisper): Fixes synchronization issue.
Sending audio while closing:

2025-05-12 19:52:17.247 SEVERE: [49476] WhisperWebsocket.onClose#280: [ctx=1747078888901486844622] Websocket closed: 1012 reason:null
2025-05-12 19:52:17.248 INFO: [205] org.eclipse.jetty.util.component.Graceful.shutdown: Shutdown WebSocketClient@15bc7f4b[coreClient=WebSocketCoreClient@2796144a{STARTED},openSessions.size=1]
2025-05-12 19:52:18.009 SEVERE: [49537] net.java.sip.communicator.util.UtilActivator.uncaughtException: An uncaught exception occurred in thread=Thread[pool-51-thread-1,5,main], and message was: Cannot invoke "java.util.Map.containsKey(Object)" because "this.participants" is null
java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "this.participants" is null
        at org.jitsi.jigasi.transcription.WhisperWebsocket.addParticipantIfNotExists(WhisperWebsocket.java:522)
        at org.jitsi.jigasi.transcription.WhisperWebsocket.addListener(WhisperWebsocket.java:533)
        at org.jitsi.jigasi.transcription.WhisperTranscriptionService$WhisperWebsocketStreamingSession.addTranscriptionListener(WhisperTranscriptionService.java:193)
        at org.jitsi.jigasi.transcription.Participant.lambda$sendRequest$1(Participant.java:717)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
2025-05-12 19:52:19.470 SEVERE: [49680] net.java.sip.communicator.util.UtilActivator.uncaughtException: An uncaught exception occurred in thread=Thread[p