fix: NPE when sip participants is leaving the call.
SEVERE: [108354] org.jitsi.jigasi.util.Util.lambda$injectSoundFile$0().295 Error playing:sounds/ParticipantLeft.opus
org.jitsi.service.neomedia.TransmissionFailedException: java.lang.NullPointerException
	at org.jitsi.impl.neomedia.MediaStreamImpl.injectPacket(MediaStreamImpl.java:3775)
	at org.jitsi.jigasi.SoundNotificationManager.injectSoundFileInStream(SoundNotificationManager.java:349)
	at org.jitsi.jigasi.SoundNotificationManager.lambda$injectSoundFile$0(SoundNotificationManager.java:290)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.jitsi.impl.neomedia.MediaStreamImpl.injectPacket(MediaStreamImpl.java:3767)
	... 3 more