feat: Drops component and configures mucs by default (#325)
* fix: Fixes 'Operation not permitted' on startup.

java.nio.file.FileSystemException: /etc/jitsi/jigasi: Operation not permitted

* fix: Start after install.

* feat: Drops component and enables control muc by default.

* squash: changes if

* squash: changes to use only adduser

* squash: Fix new name JIGASI_XMPP_PASSWORD_BASE64 in README.

* squash: Rename jicofo config.